### ISSUE TITLE
lapels 1.1.1 installation error

### ISSUE THREAD

**Issue by AlicePsyche** [shunping/lapels#1]
Hi, 

I tried to upgrade lapels to the latest but failed. Either on Linux or Mac the error is same, something related with gcc and pysam. 

```
Failed building wheel for pysam
# Linux
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -Isamtools -Ipysam -I/data4/bingjie/software/anaconda/include/python2.7 -c pysam/csamtools.c -o build/temp.linux-x86_64-2.7/pysam/csamtools.o
    pysam/csamtools.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of pysam
Command "/software/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gcyBB8/pysam/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SxhxAb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-gcyBB8/pysam/

#Mac
gcc -fno-strict-aliasing -I/Users/Alice/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -Isamtools -Ipysam -I/Users/Alice/anaconda2/include/python2.7 -c pysam/csamtools.c -o build/temp.macosx-10.5-x86_64-2.7/pysam/csamtools.o
    pysam/csamtools.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
    #error Do not use this file, it is the result of a failed Cython compilation.
     ^
    1 error generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of pysam
Command "/Users/Alice/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kx/673pgf2d0qs141_t78l9f0080000gn/T/pip-build-VZPbhD/pysam/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/kx/673pgf2d0qs141_t78l9f0080000gn/T/pip-KFjVB7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kx/673pgf2d0qs141_t78l9f0080000gn/T/pip-build-VZPbhD/pysam/

```

Could you please give me some clue that I can dig further?

**Comment by shunping** [comment]
It seems to be an incompatible issue with pysam. 
Could you try to downgrade cython to 0.20 and pysam to 0.7.6?

**Comment by AlicePsyche** [comment]
Sorry I didn't notice your installation guide before(just pip install)....After I downloaded the tar.gz file and used esay_install, the error message 

```
Traceback (most recent call last):
  File "/software/anaconda/bin/pylapels", line 5, in <module>
    pkg_resources.run_script('lapels==1.1.1', 'pylapels')
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/data4/bingjie/software/anaconda/lib/python2.7/site-packages/lapels-1.1.1-py2.7.egg/EGG-INFO/scripts/pylapels", line 13, in <module>
    import pysam
  File "/usr/local/lib/python2.7/site-packages/pysam-0.7.4-py2.7-linux-x86_64.egg/pysam/__init__.py", line 1, in <module>
    from pysam.csamtools import *
ImportError: /usr/local/lib/python2.7/site-packages/pysam-0.7.4-py2.7-linux-x86_64.egg/pysam/csamtools.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
```



I googled the error message and found an anwser here: [the official FAQ](https://docs.python.org/2.7/faq/extending.html#when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2)

> You are using a version of Python that uses a 4-byte representation for Unicode characters, but some C extension module you are importing was compiled using a Python that uses a 2-byte representation for Unicode characters (the default)

Acutally, I used lapels 1.0.7 before and had no error message. How I can fix this problem ? Or is there any possibility you could provide another version package compiled with 4-byte ? I used lapels on our school server have no root permission...

**Comment by shunping** [comment]
The error is not in Lapels, but in pysam. I guess your pysam (0.74) was compiled with an old cython that doesn't support unicode.

I would recommend you install cython 0.2.0 and pysam 0.7.6 locally.

To do that, download the packages in the following pages.
[](https://pypi.python.org/pypi/Cython/0.20)
[](https://pypi.python.org/pypi/pysam/0.7.6)

Then call easy_install with "**--user**" option, which installs the packages in your home directory.

```
easy_install --user cython-0.2.0.tar.gz
easy_install --user pysam-0.7.6.tar.gz
```

**Comment by AlicePsyche** [comment]
Thanks! I have successfully installed lapels. It works well ~

**Comment by shunping** [comment]
Great! I am closing this issue now.

**Comment by XiaoqianSun0104** [comment]
Thank you for your solution. I followed the steps and got my problem solved. @shunping
